####################################################################
# /api/register et /api/login
####################################################################

### Créer un utilisateur
### Pour la création d'un utilisateur, le id ne devrait pas être dans les données envoyées.
### Le id est créé par l'API REST et est présent dans le token.
### Pour manipuler un token, voir fichier tokenHelper.js du projet exemple-auth.
### Ci-dessous le id est ajouté pour simplifier la création, mais en réalité ce n'est pas au client de gérer la création d'un id.
POST http://localhost:3000/api/register
content-type: application/json

{
  "email": "user@user.com",
  "password": "password",
  "name": "user user",
  "id":1000,
  "role": "user"
}

### Récupérer un jeton
POST http://localhost:3000/api/login
content-type: application/json

{
  "email": "user@user.com",
  "password": "password"
}

####################################################################
# /api/users
####################################################################
# Info sur un utilisateur
GET http://localhost:3000/api/users/99999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAdXNlci5jb20iLCJpYXQiOjE2NTMyNDAwNTQsImV4cCI6MTY1MzI0MzY1NCwic3ViIjoiMTAwMCJ9.q1oe2ZZ2wfPC_OfLFzmd0dKHlmnFatU7MOlBJ8OpmUs

### Les "j'aime" d'un utilisateur
GET http://localhost:3000/api/users/1000/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAdXNlci5jb20iLCJpYXQiOjE2NTMyNDAwNTQsImV4cCI6MTY1MzI0MzY1NCwic3ViIjoiMTAwMCJ9.q1oe2ZZ2wfPC_OfLFzmd0dKHlmnFatU7MOlBJ8OpmUs


####################################################################
# /api/likes
####################################################################

### Ajouter un "j'aime" à un utilisateur
POST http://localhost:3000/api/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAdXNlci5jb20iLCJpYXQiOjE2NTMyNDAwNTQsImV4cCI6MTY1MzI0MzY1NCwic3ViIjoiMTAwMCJ9.q1oe2ZZ2wfPC_OfLFzmd0dKHlmnFatU7MOlBJ8OpmUs
content-type: application/json

{
    "userId": 1000,
    "trailId": 246
}

### supprimer un "j'aime" d'un utilisateur
DELETE  http://localhost:3000/api/likes/1056
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAdXNlci5jb20iLCJpYXQiOjE2NTMyNDAwNTQsImV4cCI6MTY1MzI0MzY1NCwic3ViIjoiMTAwMCJ9.q1oe2ZZ2wfPC_OfLFzmd0dKHlmnFatU7MOlBJ8OpmUs
